export { default } from "./src/wallet-manager-tron-gasfree.js";
export { default as WalletAccountTronGasfree } from "./src/wallet-account-tron-gasfree.js";
export type FeeRates = import("@wdk/wallet-tron").FeeRates;
export type KeyPair = import("@wdk/wallet-tron").KeyPair;
export type TronTransaction = import("@wdk/wallet-tron").TronTransaction;
export type TransactionResult = import("@wdk/wallet-tron").TransactionResult;
export type TransferOptions = import("@wdk/wallet-tron").TransferOptions;
export type TransferResult = import("@wdk/wallet-tron").TransferResult;
export type TronTransactionReceipt = import("@wdk/wallet-tron").TronTransactionReceipt;
export type TronGasFreeWalletConfig = import("./src/wallet-account-tron-gasfree.js").TronGasFreeWalletConfig;
