export { default } from "./src/wallet-manager-tron-gasfree.js";
export { default as WalletAccountReadOnlyTronGasfree } from "./src/wallet-account-read-only-tron-gasfree.js";
export { default as WalletAccountTronGasfree } from "./src/wallet-account-tron-gasfree.js";
export type FeeRates = import("@tetherto/wdk-wallet-tron").FeeRates;
export type KeyPair = import("@tetherto/wdk-wallet-tron").KeyPair;
export type TronTransaction = import("@tetherto/wdk-wallet-tron").TronTransaction;
export type TransactionResult = import("@tetherto/wdk-wallet-tron").TransactionResult;
export type TransferOptions = import("@tetherto/wdk-wallet-tron").TransferOptions;
export type TransferResult = import("@tetherto/wdk-wallet-tron").TransferResult;
export type TronTransactionReceipt = import("@tetherto/wdk-wallet-tron").TronTransactionReceipt;
export type TronActivationFee = import("@tetherto/wdk-wallet-tron").TronActivationFee;
export type Finality = import("@tetherto/wdk-wallet").Finality;
export type TransactionReceipt = import("@tetherto/wdk-wallet").TransactionReceipt;
export type WaitForTransactionTarget = import("@tetherto/wdk-wallet").WaitForTransactionTarget;
export type WaitForTransactionOptions = import("@tetherto/wdk-wallet").WaitForTransactionOptions;
export type TronGasfreeAssetInfo = import("./src/wallet-account-read-only-tron-gasfree.js").TronGasfreeAssetInfo;
export type TronGasfreeAccountInfo = import("./src/wallet-account-read-only-tron-gasfree.js").TronGasfreeAccountInfo;
export type TronGasfreeTransactionDetails = import("./src/wallet-account-read-only-tron-gasfree.js").TronGasfreeTransactionDetails;
export type TronGasfreeWalletConfig = import("./src/wallet-manager-tron-gasfree.js").TronGasfreeWalletConfig;
